apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: { name }
  name: { name }
spec:
  revisionHistoryLimit: 2
  minReadySeconds: 240
  template:
    metadata:
      labels:
        name: { name }
    spec:
      containers:
        - name: { name }
          image: skydipper/{name}
          imagePullPolicy: Always
          args:
            - start
          resources:
            requests:
              memory: '128Mi'
              cpu: '250m'
            limits:
              memory: '2Gi'
          env:
            - name: CALLBACK_URL
              value: http://skydipper.com/auth
            - name: WRI_API_URL
              value: https://api.resourcewatch.org/v1
            - name: APPLICATIONS
              value: rw
            - name: API_ENV
              value: production
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: SKYDIPPER_MANAGER_SECRET
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: REDIS_URI
            - name: CONTROL_TOWER_URL
              value: https://api.skydipper.com
            - name: BASEMAP_TILE_URL
              value:
          ports:
            - containerPort: 3000
      restartPolicy: Always
