apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: {name}
  name: {name}
spec:
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        name: {name}
    spec:
      containers:
        - name: {name}
          image: vizzuality/{name}
          imagePullPolicy: Always
          resources:
            requests:
              memory: '128Mi'
              cpu: '250m'
            limits:
              memory: '1Gi'
          env:
            - name: CALLBACK_URL
              value: http://skydipper.com/auth
            - name: WRI_API_URL
              value: https://api.skydipper.com/v1
            - name: APPLICATIONS
              value: skydipper
            - name: API_ENV
              value: production
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: appsecrets
                  key: SKYDIPPER_SECRET
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: REDIS_URI
            - name: CONTROL_TOWER_URL
              valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
            - name: BASEMAP_TILE_URL
              valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: BASEMAP_TILE_URL
          ports:
            - containerPort: 3000
      restartPolicy: Always
